spring:
 application:
    name: Account
 
 datasource:
    url: jdbc:h2:mem:testdb
    username:  yu
    password: ''
    driverClassName: org.h2.Driver
    h2:
     console:
      enable: true
      
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
  show-sql: true
    
   
    
